version: '3.8'

services:
  mariadb:
    image: xturcin0/mariadb_ads_mendelu25
    container_name: ads2025
    ports:
      - "3360:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --default-time-zone='+01:00' --innodb-buffer-pool-size=128M
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
